name: polygon-usage

on:
  schedule:
    - cron: '*/30 * * * *'
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - run: echo "ROUND=$(file=$(ls -1 config/polygon_bonus | sort --version-sort | tail -n 1); round=($(echo ${file} | tr "." "\n")); echo ${round[0]})" >> $GITHUB_ENV

      - run: go run main.go polygon-usage -c=config/polygon_bonus/${{ env.ROUND }}.json
        env:
          ETHEREUM_RPC_URL: ${{ secrets.ETHEREUM_RPC_URL }}
          POLYGON_RPC_URL: ${{ secrets.POLYGON_RPC_URL }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          POLYGONSCAN_API_KEY: ${{ secrets.POLYGONSCAN_API_KEY }}
          FURUCOMBO_PROXY_ADDRESSES: ${{ secrets.FURUCOMBO_PROXY_ADDRESSES }}
          FURUCOMBO_DSPROXY_ADDRESSES: ${{ secrets.FURUCOMBO_DSPROXY_ADDRESSES }}
          POLYGON_FURUCOMBO_PROXY_ADDRESSES: ${{ secrets.POLYGON_FURUCOMBO_PROXY_ADDRESSES }}

      - name: Upload polygon_blocks.json to gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_ACCESS_TOKEN }}
          gist_id: 312c3e7219098007e3df6e404c36519b
          gist_file_name: polygon_blocks.json
          file_path: ./rewards/polygon_bonus/${{ env.ROUND }}/polygon_blocks.json

      - name: Upload bridge_txs.json to gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_ACCESS_TOKEN }}
          gist_id: 312c3e7219098007e3df6e404c36519b
          gist_file_name: bridge_txs.json
          file_path: ./rewards/polygon_bonus/${{ env.ROUND }}/bridge_txs.json

      - name: Upload txs.json to gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_ACCESS_TOKEN }}
          gist_id: 312c3e7219098007e3df6e404c36519b
          gist_file_name: txs.json
          file_path: ./rewards/polygon_bonus/${{ env.ROUND }}/txs.json

      - name: Upload trading_loyalty.json to gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_ACCESS_TOKEN }}
          gist_id: 312c3e7219098007e3df6e404c36519b
          gist_file_name: trading_loyalty.json
          file_path: ./rewards/polygon_bonus/${{ env.ROUND }}/trading_loyalty.json
